### ISSUE TITLE
No gifos detected

### ISSUE THREAD

**Issue by Bryan-Campuzano** [x0rzavi/github-readme-terminal#9]
![imagen](https://github.com/user-attachments/assets/473fccd7-5e05-4de2-b680-c4a0c0a4dcae)
i try to run my main.py base on files of another users to create the gif, i install the utilitie on a virtual enviroment of python for run pip and this error apears. i try to install the library, clone the repo and use this locally and dont work, i've all installed but doesn't work.

**Comment by Bryan-Campuzano** [comment]
i see into the current instalation of the proyect and gifos is there, i don't know why the program dont find them 
![imagen](https://github.com/user-attachments/assets/c36fabfa-7e64-4357-bdaa-fce08bd6cc9b)

**Comment by x0rzavi** [comment]
Maybe there's some issue with your PATH setup, can you try installing any other command line python tool and make sure it works?

**Comment by Bryan-Campuzano** [comment]
> Maybe there's some issue with your PATH setup, can you try installing any other command line python tool and make sure it works?

i'm trying to install other python version to match the version between the system and the used by the proyect using pyenv, later i'll update

**Comment by Bryan-Campuzano** [comment]
> > Maybe there's some issue with your PATH setup, can you try installing any other command line python tool and make sure it works?
> 
> i'm trying to install other python version to match the version between the system and the used by the proyect using pyenv, later i'll update

finally done jajaaj, only some troubles config all the stuff by finally done. i update the sistem and the problem was that i try to run the file some folders up, i open only the proyect folder and apparentlly works since that, beautyfull project dude. tnks a lot.

**Comment by x0rzavi** [comment]
Glad to hear that it worked :D
